In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Salary_Data.csv to Salary_Data.csv


### Load dataset

In [ ]:
dataset = pd.read_csv('Salary_Data.csv')
print(dataset)

    Age  Salary  Status
0    21   39343       0
1    21   46205       1
2    21   37731       1
3    22   43525       1
4    22   39891       1
5    23   56642       0
6    23   60150       1
7    23   54445       0
8    23   64445       1
9    23   57189       0
10   23   63218       0
11   24   55794       1
12   24   56957       0
13   24   57081       0
14   25   61111       0
15   25   67938       1
16   26   66029       0
17   27   83088       0
18   28   81363       0
19   29   93940       1
20   30   91738       0
21   30   98273       0
22   31  101302       0
23   32  113812       0
24   33  109431       1
25   34  105582       1
26   35  116969       0
27   36  112635       0
28   37  122391       0
29   38  121872       1


### Segregating Dataset into x and y

In [ ]:
X = dataset.iloc[:, :-1].values
X

array([[    21,  39343],
       [    21,  46205],
       [    21,  37731],
       [    22,  43525],
       [    22,  39891],
       [    23,  56642],
       [    23,  60150],
       [    23,  54445],
       [    23,  64445],
       [    23,  57189],
       [    23,  63218],
       [    24,  55794],
       [    24,  56957],
       [    24,  57081],
       [    25,  61111],
       [    25,  67938],
       [    26,  66029],
       [    27,  83088],
       [    28,  81363],
       [    29,  93940],
       [    30,  91738],
       [    30,  98273],
       [    31, 101302],
       [    32, 113812],
       [    33, 109431],
       [    34, 105582],
       [    35, 116969],
       [    36, 112635],
       [    37, 122391],
       [    38, 121872]])

In [ ]:
Y = dataset.iloc[:, -1].values
Y

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1])

### Splitting dataset into train & test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

## featuring scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[ 0.14147911  0.41869024]
 [ 1.03077641  1.17070968]
 [-0.74781818 -0.67321193]
 [-0.08084521 -0.28564157]
 [-0.74781818 -0.35104175]
 [-0.30316953 -0.4886959 ]
 [ 1.25310073  1.68722242]
 [ 0.80845208  0.77583135]
 [-1.19246682 -1.10413467]
 [ 2.58704667  2.02000362]
 [-0.74781818 -0.52837366]
 [-0.9701425  -1.36482703]
 [ 0.36380344  0.34746846]
 [ 0.58612776  0.8667475 ]
 [-0.74781818 -0.6506274 ]
 [-0.74781818 -0.76392164]
 [ 1.69774938  1.34742227]
 [-0.9701425  -1.21478648]
 [-1.19246682 -1.38745285]
 [ 0.80845208  1.04564836]
 [-0.30316953 -0.2068228 ]
 [-0.52549385 -0.66020621]]


### Training

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train, Y_train)

LogisticRegression(random_state=0)

### Prediction 

In [ ]:
age = int(input("Enter new Customer's age: "))
sal = int(input("Enter new Cutomer's sal: "))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer will buy")
else:
  print("Customer won't buy")


Enter new Customer's age: 21
Enter new Cutomer's sal: 12345
[0]
Customer won't buy


### Prediction for all test data

In [ ]:
Y_pred = model.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]]


### Accuracy of the result

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print("Confusion matrix: ")
print(cm)
print("Accuracy of the model: {0}%".format(accuracy_score(Y_test, Y_pred)*100))


Confusion matrix: 
[[5 0]
 [3 0]]
Accuracy of the model: 62.5%
